apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dell-fan-controller.secretName" . }}
  labels:
    {{- include "dell-fan-controller.labels" . | nindent 4 }}
type: Opaque
data:
  IDRAC_HOST: {{ .Values.server.host | toString | b64enc }}
  IDRAC_USERNAME: {{ .Values.server.username | toString | b64enc }}
  IDRAC_PASSWORD: {{ .Values.server.password | toString | b64enc }}
  FAN_SPEED: {{ .Values.server.fan_speed | toString | b64enc }}
  CPU_TEMPERATURE_THRESHOLD: {{ .Values.server.cpu_temperature_threshold | toString | b64enc }}
  CHECK_INTERVAL: {{ .Values.server.check_interval | toString | b64enc }}
  DISABLE_THIRD_PARTY_PCIE_CARD_DELL_DEFAULT_COOLING_RESPONSE: {{ .Values.server.disable_pcie_cooling | toString | b64enc }}
  KEEP_THIRD_PARTY_PCIE_CARD_COOLING_RESPONSE_STATE_ON_EXIT: {{ .Values.server.keep_pcie_cooling | toString | b64enc }}
