apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: prometheus-pve-exporter
description: prometheus-pve-exporter helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "3.5.0"
maintainers:
  - name: AlexMorbo
    email: alex@morbo.ru
sources:
  - https://github.com/alexmorbo/helm-charts/tree/master/charts/prometheus-pve-exporter
home: https://github.com/prometheus-pve/prometheus-pve-exporter