{{- if .Values.qbittorrent.metrics.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qbittorrent.fullname" . }}-exporter
  labels:
    {{- include "qbittorrent.labels" (dict "component" "exporter" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: {{ .Values.qbittorrent.metrics.updateStrategy.type | default "Recreate" }}
  selector:
    matchLabels:
      {{- include "qbittorrent.selectorLabels" (dict "component" "exporter" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 6 }}
  template:
    metadata:
      {{- with .Values.qbittorrent.metrics.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "qbittorrent.labels" (dict "component" "exporter" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 8 }}
        {{- with .Values.qbittorrent.metrics.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.qbittorrent.metrics.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "qbittorrent.serviceAccountName" . }}
      {{- with .Values.qbittorrent.metrics.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: exporter
          {{- if .Values.qbittorrent.metrics.image.sha }}
          image: "{{ .Values.qbittorrent.metrics.image.registry }}/{{ .Values.qbittorrent.metrics.image.repository }}:{{ .Values.qbittorrent.metrics.image.tag }}@sha256:{{ .Values.qbittorrent.metrics.image.sha }}"
          {{- else }}
          image: "{{ .Values.qbittorrent.metrics.image.registry }}/{{ .Values.qbittorrent.metrics.image.repository }}:{{ .Values.qbittorrent.metrics.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.qbittorrent.metrics.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.qbittorrent.metrics.service.port }}
              protocol: TCP
          {{- with .Values.qbittorrent.metrics.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: QBITTORRENT_HOST
              value: "{{ include "qbittorrent.fullname" . }}-web"
            - name: QBITTORRENT_PORT
              value: "{{ .Values.qbittorrent.service.web.port }}"
            - name: EXPORTER_PORT
              value: "{{ .Values.qbittorrent.metrics.service.port }}"
          {{- with .Values.qbittorrent.metrics.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.qbittorrent.metrics.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.qbittorrent.metrics.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.qbittorrent.metrics.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.qbittorrent.metrics.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.qbittorrent.metrics.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
