{{- if .Values.qbittorrent.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qbittorrent.fullname" . }}-exporter
  labels:
    {{- include "qbittorrent.labels" (dict "component" "exporter" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.qbittorrent.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "qbittorrent.selectorLabels" (dict "component" "exporter" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 4 }}
{{- end }}
