{{- if .Values.qbittorrent.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qbittorrent.fullname" . }}-exporter
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
    app.kubernetes.io/component: exporter
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.qbittorrent.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "qbittorrent.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: exporter
{{- end }}
