{{- if .Values.qbittorrent.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "qbittorrent.fullname" . }}-exporter
  labels:
    {{- include "qbittorrent.labels" (dict "component" "exporter" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "qbittorrent.selectorLabels" (dict "component" "exporter" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 4 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      interval: {{ .Values.qbittorrent.metrics.serviceMonitor.interval | default "30s" }}
      scrapeTimeout: {{ .Values.qbittorrent.metrics.serviceMonitor.scrapeTimeout | default "10s" }}
      scheme: {{ .Values.qbittorrent.metrics.serviceMonitor.scheme | default "http" }}
      tlsConfig:
        {{- toYaml .Values.qbittorrent.metrics.serviceMonitor.tlsConfig | nindent 8 }}
      relabelings:
        {{- toYaml .Values.qbittorrent.metrics.serviceMonitor.relabelings | nindent 8 }}
{{- end }}
