{{- if .Values.qbittorrent.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "qbittorrent.fullname" . }}-exporter
  labels:
    {{- include "qbittorrent.labels" (dict "component" "exporter" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "qbittorrent.selectorLabels" (dict "component" "exporter" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 6 }}
  endpoints:
    - port: metrics
      path: /
      {{- with .Values.qbittorrent.metrics.serviceMonitor.interval | default "30s" }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.qbittorrent.metrics.serviceMonitor.scrapeTimeout | default "10s" }}
      scrapeTimeout: {{ . }}
      {{- end }}
{{- end }}
