{{- if .Values.manage.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "manage.configMapName" . }}
  labels:
    {{- include "qbittorrent.labels" (dict "component" "manage" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 4 }}
data:
  config.yml: |
    {{ .Values.manage.config | toYaml | nindent 4 }}
{{- end }}
