{{- if .Values.manage.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "manage.configMapName" . }}
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
    app.kubernetes.io/component: manage
data:
  config.yml: |
    {{ .Values.manage.config | toYaml | nindent 4 }}
{{- end }}
