{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lldap.secretName" . }}
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  lldap-jwt-secret: {{ .Values.secret.lldapJwtSecret | b64enc }}
  lldap-ldap-user-pass: {{ .Values.secret.lldapUserPass | b64enc }}
  base-dn: {{ .Values.secret.lldapBaseDn | b64enc }}
{{- end }}
