apiVersion: v1
kind: Service
metadata:
  name: {{ include "lldap.serviceName" . }}
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ldap_port }}
      targetPort: ldap
      protocol: TCP
      name: ldap
    - port: {{ .Values.service.http_port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lldap.selectorLabels" . | nindent 4 }}
  ipFamilyPolicy: PreferDualStack
