{{- if .Values.proxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pushprox.fullname" . }}-proxy
  labels:
    {{- include "pushprox.labels" (dict "component" "proxy" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 4 }}
  {{- with .Values.proxy.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.proxy.replicaCount }}
  selector:
    matchLabels:
      {{- include "pushprox.labels" (dict "component" "proxy" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 6 }}
  strategy:
    type: {{ .Values.proxy.updateStrategy.type }}
  template:
    metadata:
      labels:
        {{- include "pushprox.labels" (dict "component" "proxy" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 8 }}
        {{- with .Values.proxy.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.proxy.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.proxy.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pushprox.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.proxy.podSecurityContext | nindent 8 }}
      {{- with .Values.proxy.extraInitContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.proxy.image.sha }}
          image: "{{ .Values.proxy.image.registry }}/{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag | default (printf "v%s" .Chart.AppVersion) }}@sha256:{{ .Values.proxy.image.sha }}"
          {{- else }}
          image: "{{ .Values.proxy.image.registry }}/{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag | default (printf "v%s" .Chart.AppVersion) }}"
          {{- end }}
          {{- range .Values.proxy.command }}
          command:
            - {{ . | quote }}
          {{- end }}
          imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
          {{- with .Values.proxy.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.proxy.env .Values.proxy.extraEnv }}
          env:
            {{- range $key, $value := .Values.proxy.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range .Values.proxy.extraEnv }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
          {{- with .Values.proxy.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.proxy.service.containerPort }}
              protocol: TCP
          {{- with .Values.proxy.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.proxy.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
