{{- if .Values.proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pushprox.serviceName" . }}
  labels:
    {{- include "pushprox.labels" (dict "component" "proxy" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 4 }}
  {{- with .Values.proxy.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
    - port: {{ .Values.proxy.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pushprox.selectorLabels" (dict "component" "proxy" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 4 }}
  ipFamilyPolicy: PreferDualStack
{{- end }}
