apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: lldap
description: LLDAP helm chart for Kubernetes
type: application
version: 1.0.5
appVersion: "2025-05-19-alpine"
maintainers:
  - name: AlexMorbo
    email: alex@morbo.ru
sources:
  - https://github.com/alexmorbo/helm-charts/tree/master/charts/lldap
icon: https://raw.githubusercontent.com/alexmorbo/helm-charts/refs/heads/master/docs/assets/logo.svg
home: https://github.com/alexmorbo/helm-charts
keywords:
  - ldap
  - lldap
  - user-management
  - auth
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/lldap/lldap
    - name: Chart Source
      url: https://github.com/alexmorbo/helm-charts/tree/master/charts/lldap
  artifacthub.io/images: |
    - name: lldap
      image: lldap/lldap:2025-05-19-alpine
