apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-pve-exporter.configMapName" . }}
  labels:
    {{- include "prometheus-pve-exporter.labels" . | nindent 4 }}
data:
  pve.yml: |
    {{- range $moduleName, $module := .Values.modules }}
      {{ $moduleName }}:
        user: {{ index (split "!" $module.token_id) "_0" }}
        token_name: {{ index (split "!" $module.token_id) "_1" }}
        token_value: {{ $module.token_secret }}
    {{- end }}
