apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-pve-exporter.serviceName" . }}
  labels:
    {{- include "prometheus-pve-exporter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "prometheus-pve-exporter.servicePort" . }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "prometheus-pve-exporter.selectorLabels" . | nindent 4 }}
  ipFamilyPolicy: PreferDualStack
