apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: esphome
description: Esphome helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "2024.12.2"
maintainers:
  - name: AlexMorbo
    email: alex@morbo.ru
sources:
  - https://github.com/alexmorbo/helm-charts/tree/master/charts/esphome
icon: https://raw.githubusercontent.com/alexmorbo/helm-charts/refs/heads/master/docs/assets/logo.svg
home: https://github.com/alexmorbo/helm-charts
keywords:
  - esphome
  - home-assistant
  - home-automation
  - home-assistant-addons
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/esphome/esphome
    - name: Chart Source
      url: https://github.com/alexmorbo/helm-charts/tree/master/charts/esphome
